### ISSUE TITLE
Disable routes for components which are not active

### ISSUE THREAD

**Issue by ljupcovangelski** [airyhq/airy#2143] opened 2021-07-09 16:26 UTC
The `webhooks.subscribe` route returns 200 even if the `integration-webhook` component is disabled.
We need to make sure that we return a proper status code.

**Comment by chrismatix** [comment] 2021-07-12 09:10
I'd propose returning `409 (Conflict)`

**Comment by chrismatix** [comment] 2021-07-23 12:54
Duplicate of #2140

**Closed by chrismatix** 2021-07-23 12:54 UTC
Labels: backend
