### ISSUE TITLE
Templates UI

### ISSUE THREAD

**Issue by isabelaabrantes** [airyhq/airy#600] opened 2021-01-08 14:32 UTC
# Summary

To get a better conversation experience, one agent could have the possibility of sending pre-saved messages on an on-going conversation. (Besides increasing the efficiency and consistency of answers from an agent, this feature should be the basis for, in the future, allow our core platform to be able to provide suggestions responses for agents).

# Requirements 

We have two main types of "saved replies" use cases, the one we usually called _templates or rich cards_, now being called _custom format_ and the _plain text_ messages. Each one has specific use cases related, so differentiation is needed.

**Types of saved replies**
----

### Plain text

On a saved reply plain-text type:
- the content should appear in the conversation history
- should be inserted in the message input field, allowing users to edit before send if needed
- ideally should be agnostic, allowing users to apply them to all source types* 

![image](https://user-images.githubusercontent.com/62546132/104713559-59163980-5724-11eb-8c78-5918a3abcd95.png)
_plain text use case: just text content; possibility of edit a message before sending it, the display of the message does not depend on the source requirements_

**⚠️ *TBD: For the plain text type, we ideally should go for a source-agnostic approach. It will avoid redundancy on our costumers' content management and prepare us to have "suggested r future.**  

 ### Custom formats

- a _custom-type_ should always be source-related once it could have specific content fields (which could be mandatory or not, according to the source definitions) inherited from the source where the conversation starts. 
- the custom format doesn't need to be rendered but should appear on a conversation when sent, ideally with a plain text warning and a custom format identification (saved reply id?) 
- it should be sent immediately once it doesn't allow any edition in the content

![image](https://user-images.githubusercontent.com/62546132/104714531-98915580-5725-11eb-8c80-f66a8bc2b090.png)
_custom format use case: possibility of different formats for each source, closely attached to the source of the conversation requirements; should be sent without the possibility of edition_

**Triggering saved replies**
----

- we should be able to **trigger a saved reply;** that could be triggered in two ways:

      - by an agent action, in any moment of an existing conversation: 
![image](https://user-images.githubusercontent.com/62546132/104716601-7220e980-5728-11eb-9d03-4140badd78d8.png)
_example of how an agent could manually send a saved reply_ 

      - automatically triggered by a specific postback of a previous message on an existing conversation:
![image](https://user-images.githubusercontent.com/62546132/104716483-4b62b300-5728-11eb-963d-31b08215f877.png)
_example of a previous message that automatically will trigger a saved reply on the conversation_

**Saved replies creation and management**
----

-  we are NOT supposed to manage the **custom-type** saved replies (once the possibilities are many, source-related and non-agnostic). Still, we should create a way to allow other applications (custom apps?) to integrate with our core application to enhance this experience in the future with the possibility of:

 1. create and manage custom-type saved replies for each source (through our API and/or through the UI)
 
 2. display the preview of this custom-type saved replies inside the agent's view application (Inbox's UI) on the saved replies options list and/or inside the conversation;

**Tracking and monitoring**
----

It's essential to understand that we need to track and display the usage of the "saved replies" to: 

- to know how often a "saved reply" was used (we should display that a saved reply was triggered in the conversation, even when we aren't able to render it); _, e.g., nowadays, we don't render all the "custom-type" templates on the agent's view, and we don't provide any information about this in the conversation, which can mislead the agent;_ 

![image](https://user-images.githubusercontent.com/62546132/104749743-78788b00-5753-11eb-95c4-7fa48fa4ab0e.png)
_mockup of a possible way to inform an agent about a custom-type message sent_

- to further use this data to suggest a "saved reply" to be used by the agent
![image](https://user-images.githubusercontent.com/62546132/104750214-10767480-5754-11eb-9e5d-3362ac76e195.png)
_mockup of a possible way to suggest an agent about a saved reply_

- to increase analytics and custom data for our customers

**Payload content suggestion** 
----

Each saved reply could have:
- a unique id;
- a content-type definition, if it is a text-type or a custom-type;
- the message content payload (based on source payload definitions);
- additional metadata to help us to:
 - track a "saved reply" to use this information further to improve, analyze, and/or generate internal or product data about the messaging/feature usage
 - set up further features that could be triggered by a saved reply (e.g., disable the input text field after a saved reply that contains a template with buttons where the user should only choose one of the options [check image below])

![image](https://user-images.githubusercontent.com/62546132/104425152-99d54d80-5580-11eb-85a3-043708edd339.png)
_example of changes on the interface triggered by the current content of a message_ 

----

🚫 **IMPORTANT:** Rendering custom-type saved replies on the agent side, rendering all saved replies on the client-side, and managing (create, edit and delete) custom-types are not supposed to be core features that should be added to our system by custom-app plugins. 

# Further roadmap
- Core integration that allows custom apps to add the features to manage, create and preview _custom-type saved replies_ on the agent's view
- Suggested replies (start to suggest the ideal saved reply for an agent based on the frequency of use and previous message content)
- Allow agents to use shortcuts to send saved replies (Slack alike)

**Comment by lucapette** [comment] 2021-02-03 11:02
duplicate of #677

**Closed by lucapette** 2021-02-03 11:02 UTC
Labels: feature, needs discussion
