### ISSUE TITLE
Hotfixes that don't have an issue break our convention of putting the issue in the merge message

### ISSUE THREAD

**Issue by pascal-airy** [airyhq/airy#324] opened 2020-11-18 09:32 UTC
We should discuss if we loosen our convention or make it part of a hotfix to always create an issue for it

**Comment by chrismatix** [comment] 2020-11-19 08:28
I am in favor of *loosening the convention*. 

Hotfixes can vary widely in complexity (flawed code to just typos) so not all of them need to be documented in an issue. I would argue that if there is an issue to link, we should do so and if not we can add a separate convention for the commit message. Something like `[hotfix] oh no semicolons DO have a meaning in JS`

**Comment by paulodiniz** [comment] 2020-11-19 08:42
Maybe the root of the problem is what we *define* as a hotfix.

I propose the following definition: `It's the action needed to fix a functionality that does not work in production`

Consequences of this definition are

- There must always be an issue relating to it
- We always branch from `main` (because production is part of the definition)
- There *must* be a release attached to it

Things that are not production breaking, should not demand a hotfix, therefore can be attached to a release. This definition encapsulates the "this is urgent" concept, so anything related to style/convention/would-be-nice-to-have fall outside of this category.

What do you think?

**Comment by lucapette** [comment] 2020-11-23 08:12
I agree with shouldn't loosen the convention, once we do we'll open the door to commits that work their way into a release and we can't easily track them down. 

What I suggest is to open an issue right before each release. It would serve different purposes:

- any commit in the release branch can refer to the release issue
- We can have a PR pointing to the release (with the usual `Fixes #issue-number` we also close it automatically)
- the `VERSION` bump (and the changelog updates) would neatly refer to the issue _and_ be part of the above-mentioned PR

**Closed** 2020-11-24 09:21 UTC
Labels: documentation
