### ISSUE TITLE
Payload of file messages looks wrong

### ISSUE THREAD

**Issue by bitboxer** [airyhq/airy#897] opened 2021-02-05 14:43 UTC
When I upload a file that is not an image to a message, the core returns this kind of message for the conversation for me:

```json
{
  "sender": {
    "id": "2383413815058256"
  },
  "recipient": {
    "id": "104296827616214"
  },
  "timestamp": 1612534146086,
  "message": {
    "mid": "m_XiVE-6CmpMFOLwXH_ndm0TBv30z7d5bonWa40xkWEe-kGfkjEt5XeY76eOOJL8-hpsnJBJfWAC8vOVWNWWbSnQ",
    "attachments": [
      {
        "type": "fallback",
        "payload": {
          "title": "Attachment Unavailable"
        }
      }
    ]
  }
}
```

it would be ideal if I get a link to the actual file so that we can show a download link.

**Comment by chrismatix** [comment] 2021-02-09 14:17
Hey @bitboxer I was just able to reproduce the issue you described and after some digging found the source in this [Facebook developer update](https://developers.facebook.com/docs/messenger-platform/europe-updates): _Tl;dr_ due to EU privacy regulation attachments are currently not being delivered in the messaging webhook, but they are planning to bring it back in *Q1 2021*.

I am closing this issue as there is nothing we can do about this for now.

**Closed by chrismatix** 2021-02-09 14:17 UTC
Labels: backend, bug
