### ISSUE TITLE
Render Google Rich cards on Live Chat Plugin widget

### ISSUE THREAD

**Issue by isabelaabrantes** [airyhq/airy#593] opened 2021-01-07 16:17 UTC
We need to render rich cards from GBC on our Live Chat Plugin widget. 

At first, these are the minimum requirements:
- The rich card should be rendered on the widget and will be triggered only by the API (an agent couldn't send it manually)
- The rich card only will be rendered on the customer side, not on the agent side for the moment. If possible, the agent side should only be able to see a text warning inside the conversation indicating that the "A rich card was sent to the customer". 

Once we fetch the rich cards' content, we need to render it following the UI standards of the Live Chat Plugin. So, we should follow the design specs for each element, as they are defined [on the layout files attached](https://projects.invisionapp.com/d/main?origin=v7#/projects/prototypes/20863349
). 

### Suggested replies list

- Suggested replies should be rendered as secondary buttons elements
- Suggested replies could be maximum of 4 for each rich card
- They will contain a maximum of 25 chars (which means that the line won't break on the current solution, so the height is fixed, but the width will change according to the text size)
- The alignment of the buttons should always be on the right side

![image](https://user-images.githubusercontent.com/62546132/103907540-adf0f900-5101-11eb-84bf-fce896686f18.png)

**Rich card properties [(inherit from Google definitions)](https://developers.google.com/business-communications/business-messages/guides/build/send#suggested_replies)**  
>1. Rich cards can contain the following items:
>- Media (JPG, JPEG, or PNG, maximum 5 MB)
>- Media thumbnail (JPG, JPEG or PNG, maximum 25 KB)
>- Title (maximum 200 characters)
>- Description (maximum 2000 characters)
>- A list of suggested replies and suggested actions (maximum 4)
> 2. A rich card can contain any or all of the listed items, but a card must contain at least media or a title to be valid. 
> 3. A rich card can contain a maximum of 4 suggested actions and suggested replies.

Additional documentation: https://developers.google.com/business-communications/business-messages/guides/build/send?hl=en

**Comment by lucapette** [comment] 2021-02-03 10:46
duplicate of #671

**Closed by lucapette** 2021-02-03 10:46 UTC
Labels: needs discussion
