### ISSUE TITLE
Render Survey Response Google Business Messages 

### ISSUE THREAD

**Issue by AudreyKj** [airyhq/airy#2576] opened 2021-11-11 09:09 UTC
- Render Survey response Google Business Messages (inbound message)
---> https://developers.google.com/business-communications/business-messages/guides/build/surveys

- on GBM, when the user is asked to give feedback, his/her survey response is sent as an inbound message. At the moment, we do not render this (resulting in "unsupported message type").

payload 
<img width="789" alt="Screenshot 2021-11-11 at 10 05 48" src="https://user-images.githubusercontent.com/38159391/141269941-a70481b5-d1c5-4523-944f-a533d911ba89.png">

![IMG_2604](https://user-images.githubusercontent.com/38159391/141270163-a4430e26-fb23-436c-a6de-38c826e4b4ee.jpg)

**Comment by steffh** [comment] 2021-11-12 14:45
Sorry, just have seen this ticket, so this might be a duplicate of this request: https://github.com/airyhq/airy/issues/2580

Maybe you could quickly check if the new code might also resolve this bug: https://github.com/airyhq/airy/issues/2579

**Comment by AudreyKj** [comment] 2021-11-12 14:52
@steffh yes I just fixed this rendering issue in pull request: #2578

**Closed** 2021-11-15 11:15 UTC
Labels: fix
