### ISSUE TITLE
Bug: Sending Messages to Facebook Doesn't Work

### ISSUE THREAD

**Issue by lizhutter** [airyhq/airy#1006] opened 2021-02-16 18:31 UTC
Receiving messages from Facebook works, but sending messages to Facebook doesn’t work.

![screenshot_2021-02-16_at_18 59 27](https://user-images.githubusercontent.com/74183162/108103843-c8b47700-708a-11eb-8256-bfd8877d91ff.png)

**Comment by lucapette** [comment] 2021-02-17 15:00
I didn't label this yet as we're not providing enough information about it. It's hard to say what this is about. do we know if core receives the message correctly and we can't relay it back to facebook or it's "just" a frontend problem and we can't send the message?

**Comment by AitorAlgorta** [comment] 2021-02-18 10:10
I will dig into it

**Comment by steffh** [comment] 2021-02-18 15:08
it happened to me also trying to send messages via the API, so i think it's not a frontend only bug...

**Comment by AitorAlgorta** [comment] 2021-02-18 15:25
Jumping into it now @steffh

**Comment by AitorAlgorta** [comment] 2021-02-18 16:40
![Screenshot 2021-02-18 at 17 39 31](https://user-images.githubusercontent.com/6797037/108389806-4eadfa80-7210-11eb-9abf-576ff8389e31.png)

**Comment by AitorAlgorta** [comment] 2021-02-18 16:41
I got `200` from the UI, but the message never got to Facebook

**Comment by AitorAlgorta** [comment] 2021-02-18 16:52
so, I sent a message from Insomnia, and it appeared in the UI, but not in Facebook. Messages from UI also get rendered in the UI, but not appearing in Facebook. Messages from Facebook are appearing in the UI. Looks more a backend thing.

**Comment by AitorAlgorta** [comment] 2021-02-18 16:54
or maybe the payload is incorrect? I am not sure

**Comment by AitorAlgorta** [comment] 2021-02-19 08:37
I think we identified the problem @steffh. Looks like the payloads for send text messages that you added to this ticket (https://zube.io/airy/platform/c/8733) are wrong.

**Comment by AitorAlgorta** [comment] 2021-02-19 08:37
If you can provide the correct payloads for each source we will fix it

**Comment by lucapette** [comment] 2021-02-22 10:19
duplicate of #1042

**Closed by lucapette** 2021-02-22 10:19 UTC
