### ISSUE TITLE
Render Suggested Replies

### ISSUE THREAD

**Issue by lizhutter** [airyhq/airy#677] opened 2021-01-18 17:04 UTC
### Summary

The following criteria must be met for each suggested reply to be eligible to be rendered:
- ID
- name
- source type (This is necessary because we have to know for which source they are. We need to make it possible to have some replies that are source agnostic.)
- content (This will be very source specific, so our system should accept whatever JSON is saved because there is no CMS feature on our side.)

### Requirements

If a question is received by a system user on Airy Core, it should be possible to view suggested replies. If a system user clicks the suggested reply modal, we should offer the option of one or several reply options. Once the system user selects a suggested reply to send, it should auto-fill the input bar and the system user should be able to send this message.

![02 0 Suggested Replies one option@2x](https://user-images.githubusercontent.com/74183162/106909707-d66c1300-6700-11eb-8b3a-9c49618fbd3c.png)
![02 1 Suggested Replies one option@2x](https://user-images.githubusercontent.com/74183162/106909713-d79d4000-6700-11eb-8642-215244eb41d3.png)
![02 2 Suggested Replies one option@2x](https://user-images.githubusercontent.com/74183162/106909720-d835d680-6700-11eb-8ef8-632bffeec243.png)
![01 0 Suggested Replies – many options@2x](https://user-images.githubusercontent.com/74183162/106907850-fc90b380-66fe-11eb-93a6-195649f2f51c.png)
![01 1 0 Suggested Replies – many options@2x](https://user-images.githubusercontent.com/74183162/106907864-ff8ba400-66fe-11eb-9b94-6006a6490112.png)
![01 1 1 Suggested Replies – many options@2x](https://user-images.githubusercontent.com/74183162/106907872-00bcd100-66ff-11eb-921d-0aed573d8439.png)
![01 2 Suggested Replies@2x](https://user-images.githubusercontent.com/74183162/106907877-01edfe00-66ff-11eb-84e7-e0c65d90ca24.png)
![01 3 Suggested Replies@2x](https://user-images.githubusercontent.com/74183162/106907881-031f2b00-66ff-11eb-828c-6069d173c250.png)

We need to be able to render different types of templates regardless of whether they are composed of text, media, or buttons.

![03 0 Suggested Replies – Templates@2x](https://user-images.githubusercontent.com/74183162/106909903-01566700-6701-11eb-937a-e9b3c5f4975a.png)
![03 1 Suggested Replies – Templates@2x](https://user-images.githubusercontent.com/74183162/106909910-03b8c100-6701-11eb-8955-8beff04fa9fc.png)
![03 2 Suggested Replies – Templates@2x](https://user-images.githubusercontent.com/74183162/106909919-04e9ee00-6701-11eb-99bc-9edd146dae1c.png)

We should be able to render templates composed of long messages. We should be able to display a cropped view of these replies and furthermore, system users should be able to send these messages in full.

![04 0 Long message crop@2x](https://user-images.githubusercontent.com/74183162/106911527-85f5b500-6702-11eb-9429-44c4b5abd8af.png)

It should be possible for system users to be prompted with more than 1 intent. The system user should be able to choose from these replies and send the message.

![05 0 Suggested Replies – more than one intent@2x](https://user-images.githubusercontent.com/74183162/106911537-89893c00-6702-11eb-85eb-bf8dc06c7207.png)

### Design Note

When creating this feature, we should only include the template button within the input bar. Do not include the template button next to the suggested replies.

**Comment by lucapette** [comment] 2021-02-03 10:55
duplicate of #600

**Comment by lucapette** [comment] 2021-02-10 15:21
As I understand it, @steffh suggested (and we agreed) that the suggested replies are message specific. The UI seems designed in a way that you can suggest replies to a conversation. It's technically not that different for the backend (but still needs to be clarified). It's surely very different in the UI?

**Comment by lizhutter** [comment] 2021-02-15 09:42
In order for suggested replies to work:
- we should always check if the last message from contact has suggested replies. If it does, we override the current suggested replies (if there are any).
- if the last message from contact doesn’t have suggested replies, we will use the suggested replies we have saved in redux (if we have) and if the suggested replies saved are no older than 5 messages.
- if we don’t have suggested replies and the last message of the contact doesn't either, then we don’t display. This means there is no suggested replies in the last 50 messages.

**Closed** 2021-03-22 15:10 UTC
Labels: frontend/ui
