### ISSUE TITLE
Google Business Messages: Render Survey Responses in Inbox UI

### ISSUE THREAD

**Issue by steffh** [airyhq/airy#2580] opened 2021-11-12 14:35 UTC
## Is your feature request related to a problem? Please describe.

As a user working with Airy Inbox UI,
I want to be able to see the review score that a user gave in response to the previous interaction 

## Describe the solution you'd like

The following example payload in the Messages List:

```
{
      "id": "9e9e6be9-8152-510c-9542-f28fc4bcb346",
      "content": {
        "agent": "brands/974c59bf-d848-4706-994e-f76551810c3e/agents/6f5a491f-b573-4827-811f-e9fd5200aaa8",
        "conversationId": "51a94b41-489e-41b0-be92-0b98bd43f374",
        "customAgentId": "15551872-8e86-4f10-b647-311ef5ba940a",
        "context": {
          "placeId": "ChIJAe-nd3U5tkcR5yWHAVTiDoI",
          "entryPoint": "PLACESHEET",
          "userInfo": {
            "displayName": "Some Person",
            "userDeviceLocale": "de-DE"
          },
          "resolvedLocale": "de"
        },
        "surveyResponse": {
          "survey": "conversations/51a94b41-489e-41b0-be92-0b98bd43f374/surveys/0c816f34-0248-4a37-bb41-138a86e78dfc",
          "rating": "VERY_DISSATISFIED",
          "createTime": "2021-11-12T12:33:00.084976Z",
          "surveyQuestionId": "GOOGLE_DEFINED_TASK_COMPLETION",
          "questionResponseText": "Nein",
          "questionResponsePostbackData": "NO",
          "questionType": "GOOGLE_STANDARD_QUESTION",
          "questionIndex": 1,
          "totalQuestionCount": 1
        },
        "sendTime": "2021-11-12T12:33:00.699543Z"
      },
      "sent_at": "2021-11-12T12:33:00.699Z",
      "delivery_state": "delivered",
      "source": "google",
      "metadata": {},
      "from_contact": true
    }
```

should be render with the following string in cursive letters:

"The user has rated the experience with: {{RATING}}"

## Describe alternatives you've considered

-

**Comment by AudreyKj** [comment] 2021-11-12 14:59
closing this issue because it's a duplicate of  #2576

**Closed by AudreyKj** 2021-11-12 14:59 UTC
Labels: needs discussion, feature
