### ISSUE TITLE
Instagram: Echoes with Templates get appended twice to a conversation

### ISSUE THREAD

**Issue by steffh** [airyhq/airy#2477] opened 2021-10-08 19:29 UTC
## To Reproduce

1. For an Instagram account that is connected to an Airy instance 
2. Send a template to a conversation (or just interact with the bot) 
3. Whenever you should receive one template as an echo
4. There are two messages appended to the conversation (as it seems one from sending and the second one receiving the echo) - whereby one is rendered correctly and the second one rendered as "Unsupported Message Type" in the Inbox UI

## Expected behavior

A template message should only be appended only once to the conversation and rendered correctly in the Inbox UI (compare with Facebook Messenger source).

## Screenshots

<img width="373" alt="Screenshot 2021-10-08 at 21 26 30" src="https://user-images.githubusercontent.com/9045481/136614897-687e028a-b22a-4b31-80da-ce5fda68b37e.png">

Payload of `POST /messages.list` for the relevant messages:

```
[
    {
     // SECOND MESSAGE - RENDERING BROKEN
      "id": "eec23d89-d0d3-53f2-bdf8-1b2c8d44a396",
      "content": {
        "sender": {
          "id": "17841401768465053"
        },
        "recipient": {
          "id": "4368254279952197"
        },
        "timestamp": 1633710384297,
        "message": {
          "mid": "aWdfZAG1faXRlbToxOklHTWVzc2FnZAUlEOjE3ODQxNDAxNzY4NDY1MDUzOjM0MDI4MjM2Njg0MTcxMDMwMDk0OTEyODE1Mzk5NDM5MDcwOTY4NjozMDEzNjYzNzM0OTcwNjIyMTUyNjIyMTk3MzM4MTcwOTgyNAZDZD",
          "attachments": [
            {
              "type": "template",
              "payload": {
                "generic": {
                  "elements": [
                    {
                      "title": "Thanks for your interest in working with REDACTED!",
                      "subtitle": "Our team will review your request and get back to you within 24 hours.",
                      "default_action": {
                        "type": "open_url",
                        "url": "https://URL/"
                      },
                      "buttons": [
                        {
                          "type": "postback",
                          "title": "Back to Main Menu",
                          "payload": "en-get-started"
                        }
                      ]
                    }
                  ]
                }
              }
            }
          ],
          "is_echo": true
        }
      },
      "sent_at": "2021-10-08T16:26:24.297Z",
      "delivery_state": "delivered",
      "source": "instagram",
      "metadata": {},
      "from_contact": false
    },
    {
     // FIRST MESSAGE - RENDERING WORKS
      "id": "ae607ee1-9150-40bf-b8a3-d363693fca0f",
      "content": {
        "attachment": {
          "type": "template",
          "payload": {
            "elements": [
              {
                "title": "Thanks for your interest in working with REDACTED!",
                "buttons": [
                  {
                    "type": "postback",
                    "title": "Back to Main Menu",
                    "payload": "en-get-started"
                  }
                ],
                "subtitle": "Our team will review your request and get back to you within 24 hours.",
                "default_action": {
                  "url": "https://URL/",
                  "type": "web_url"
                }
              }
            ],
            "template_type": "generic"
          }
        }
      },
      "sent_at": "2021-10-08T16:26:23.403Z",
      "delivery_state": "delivered",
      "source": "instagram",
      "metadata": {
        "source": {
          "id": "aWdfZAG1faXRlbToxOklHTWVzc2FnZAUlEOjE3ODQxNDAxNzY4NDY1MDUzOjM0MDI4MjM2Njg0MTcxMDMwMDk0OTEyODE1Mzk5NDM5MDcwOTY4NjozMDEzNjYzNzM0OTcwNjIyMTUyNjIyMTk3MzM4MTcwOTgyNAZDZD"
        }
      },
      "from_contact": false
    }
]
```

## Environment

- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by chrismatix** [comment] 2021-12-16 15:50
dupe of #2434

**Closed by chrismatix** 2021-12-16 15:50 UTC
Labels: backend, bug
