### ISSUE TITLE
Global unread counter

### ISSUE THREAD

**Issue by bitboxer** [airyhq/airy#989] opened 2021-02-16 10:08 UTC
For the inbox we might want to have a global unread counter so that we can display it in the fontend.

**Comment by AitorAlgorta** [comment] 2021-02-18 10:08
After talking to @lucapette we decided to do this in the frontend **for now**. We can call  `/conversations.list` with the right filter and we will get the amount in the metadata. The problem is that this won't be updated real time.

**Comment by lucapette** [comment] 2021-03-05 15:29
While I agree with that, I think the time for #422 is coming so I will close this one now (as we'll be able to build on top of that issue once it's ready)

**Closed by lucapette** 2021-03-05 15:29 UTC
Labels: needs discussion
